// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn36TxVgXjJs_mjZkv9k5QsgRTIG_Ehk8',
    appId: '1:171009605386:web:b6980727aade35d8b544f3',
    messagingSenderId: '171009605386',
    projectId: 'class-assignment-12',
    authDomain: 'class-assignment-12.firebaseapp.com',
    storageBucket: 'class-assignment-12.firebasestorage.app',
    measurementId: 'G-9TF5VZQ7D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMoY-6FMTPL-B43HdjHE65HhlXqE-LW0',
    appId: '1:171009605386:android:70325e6b18738ed8b544f3',
    messagingSenderId: '171009605386',
    projectId: 'class-assignment-12',
    storageBucket: 'class-assignment-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZ4ZSkRUKWP1CuVATfWHw6GF9iOAIQnU',
    appId: '1:171009605386:ios:fc57d06a2b01b345b544f3',
    messagingSenderId: '171009605386',
    projectId: 'class-assignment-12',
    storageBucket: 'class-assignment-12.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZ4ZSkRUKWP1CuVATfWHw6GF9iOAIQnU',
    appId: '1:171009605386:ios:fc57d06a2b01b345b544f3',
    messagingSenderId: '171009605386',
    projectId: 'class-assignment-12',
    storageBucket: 'class-assignment-12.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn36TxVgXjJs_mjZkv9k5QsgRTIG_Ehk8',
    appId: '1:171009605386:web:6851542555862151b544f3',
    messagingSenderId: '171009605386',
    projectId: 'class-assignment-12',
    authDomain: 'class-assignment-12.firebaseapp.com',
    storageBucket: 'class-assignment-12.firebasestorage.app',
    measurementId: 'G-2P56EY05QE',
  );
}
