// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2KAvfryM6Sq39g8Dst6shNtIe3Hn6no',
    appId: '1:539047789114:web:79aac89e7ef1463a3ceb03',
    messagingSenderId: '539047789114',
    projectId: 'class-assignment-14',
    authDomain: 'class-assignment-14.firebaseapp.com',
    storageBucket: 'class-assignment-14.firebasestorage.app',
    measurementId: 'G-D2BDFQG48K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuo03Fj9DZoZldAffcCPVymDXo-_ri6Sc',
    appId: '1:539047789114:android:92590b3e0de1007b3ceb03',
    messagingSenderId: '539047789114',
    projectId: 'class-assignment-14',
    storageBucket: 'class-assignment-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nzzUHP1O1UZp_iRWO3fNfooOJAjovlg',
    appId: '1:539047789114:ios:813cff0f8c6090ed3ceb03',
    messagingSenderId: '539047789114',
    projectId: 'class-assignment-14',
    storageBucket: 'class-assignment-14.firebasestorage.app',
    iosBundleId: 'com.example.classActivity14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nzzUHP1O1UZp_iRWO3fNfooOJAjovlg',
    appId: '1:539047789114:ios:813cff0f8c6090ed3ceb03',
    messagingSenderId: '539047789114',
    projectId: 'class-assignment-14',
    storageBucket: 'class-assignment-14.firebasestorage.app',
    iosBundleId: 'com.example.classActivity14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2KAvfryM6Sq39g8Dst6shNtIe3Hn6no',
    appId: '1:539047789114:web:9fb13f4bce2400133ceb03',
    messagingSenderId: '539047789114',
    projectId: 'class-assignment-14',
    authDomain: 'class-assignment-14.firebaseapp.com',
    storageBucket: 'class-assignment-14.firebasestorage.app',
    measurementId: 'G-ET2CK3T9YE',
  );
}
